Add classes supporting requirements with distinct options
AAAlex-123/Simple-CAD-Tool pull request #64
Opened 2021-07-29 13:34 UTC by dimits-exe

2021-08-04 11:06 UTC, AAAlex-123 requested changes
Can't compile.

List Requirements can be used:
 - File Menu: open, import (Find all appropriate files (ending in .scad) from directory. Languages.java has some code that may help).
 - Whenever an id of an already created component is needed (Find all Components from the Editor. Optionally filter them to display only the ones that are applicable for the specific operation. Not necessary, since checks already exist.).
 - Language selection (Tweak the pop-up dialog).

For every change:
 - Remove unused code, possibly from other classes
 - Use existing externalized Strings
 - Test everything to make sure that nothing broke and all checks and error messages work as before.

2021-08-14 14:55 UTC, AAAlex-123 commented on src/localisation/Languages.java
> +
Use the same Languages.getString() parameters as the previous version

2021-08-14 14:58 UTC, AAAlex-123 commented on src/requirement/requirements/Requirements.java
> +	public void addComponentReq(String key, List<components.Component> components) {
rename to add(String key, List<Component> components) 🔪

2021-08-14 15:01 UTC, dimits-exe commented on src/localisation/Languages.java
> +
οχι 😎

2021-08-21 15:04 UTC, AAAlex-123 commented on src/application/editor/Actions.java
> +		}
Wrong place, already implemented in DeleteCommand#fillRequirements(Frame, Editor).

2021-08-25 08:02 UTC, AAAlex-123 approved these changes
Looks good 👍

2021-08-25 08:07 UTC, merged